# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source'https://github.com/CocoaPods/Specs.git'

target 'cooplaniOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cooplaniOS
  	pod 'AFNetworking', '~> 3.1.0'
	pod 'Masonry', '~>1.0'
	pod 'SDWebImage', '~> 3.8.2'
	pod 'MJRefresh', '~> 3.1.1'	
	pod 'MJExtension', '~> 3.0.7'
	pod 'SVProgressHUD' ,'~>2.2.5'
	pod 'SDCycleScrollView','~> 1.64'
	pod 'IQKeyboardManager', '~> 3.3.4'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'TYAttributedLabel', '~> 2.6.2'
    pod 'Bugly'
    pod 'YYText'
    pod 'LYEmptyView'
    pod 'YJLocationPicker'
    pod 'WMPlayer'
    pod 'JPush'
    pod 'VBFPopFlatButton'
    pod 'JRDB'
    pod 'TZImagePickerController'
    pod 'Popover.OC'
    pod 'UMCCommon'
    pod 'UMCAnalytics'
#    pod 'UMCSecurityPlugins'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
    pod 'AlibcTradeSDK'
    
  target 'cooplaniOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cooplaniOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
